#!/usr/bin/env python3

import nexpose
import nexposeargs

def main():
    """
    Parse arguments
    """
    parser = nexposeargs.parser
    parser.description = "Get Nexpose engine pools"
    args = parser.parse_args()

    base_url = ':'.join([args.baseurl, args.port])

    login = nexpose.nsclogin(
        base_url=base_url,
        user=args.user,
        password=args.password,
        verify=args.verify,
    )

    engine_pools = nexpose.engine_pools(login=login)

    print(engine_pools)


if __name__ == "__main__":
    main()
