#!/usr/bin/env python3

import nexpose
import nexposeargs
import get_credentials


def main():
    """
    Parse arguments
    """
    parser = nexposeargs.parser
    parser.description = "Get Nexpose engine pools"
    args = parser.parse_args()

    user = args.user or get_credentials.user()
    password = args.password or get_credentials.password()
    base_url = ':'.join([args.baseurl, args.port])
    verify = args.verify

    login = nexpose.nsclogin(
        base_url=base_url,
        user=user,
        password=password,
        verify=verify,
    )

    engine_pools = nexpose.engine_pools(login=login)

    print(engine_pools)


if __name__ == "__main__":
    main()
