#!/usr/bin/env python3

import nexpose
import nexposeargs
import get_credentials

def main():
    """
    Parse arguments
    """
    parser = nexposeargs.parser
    parser.description = "Make priviledges sufficient to monitor Nexpose"
    args = parser.parse_args()

    user = args.user or get_credentials.user()
    password = args.password or get_credentials.password()
    base_url = ":".join([args.baseurl, args.port])
    verify = args.verify

    login = nexpose.nsclogin(
        base_url=base_url,
        user=user,
        password=password,
        verify=verify,
    )

    role = {
        "description": "Read-only privileges adequate for monitoring health",
        "id": "monitor",
        "name": "monitor",
        "privileges": ["view-asset-group-asset-data", "view-site-asset-data"]
        }

    print(nexpose.create_role(login=login, role=role))

if __name__ == "__main__":
    main()
