#!/usr/bin/env python3

import nexpose
import nexposeargs
import get_credentials

def main():
    """
    Parse arguments
    """
    parser = nexposeargs.parser
    parser.description = "Remove old Nexpose reports"

    args = parser.parse_args()

    user = args.user or get_credentials.user()
    password = args.password or get_credentials.password()
    base_url = ':'.join([args.baseurl, args.port])
    verify = args.verify

    login = nexpose.nsclogin(
        base_url=base_url,
        user=user,
        password=password,
        verify=verify,
    )

    pages = nexpose.reports(login=login)["page"]["totalPages"]

    for page in range(pages):
        resources = nexpose.reports(login=login, page=page)["resources"]
        report_ids = [resource['id'] for resource in resources]
        for report_id in report_ids:
            history = nexpose.report_history(login=login, report_id=report_id)
            if len(history['resources']) == 0:
                nexpose.delete_report(login=login, report_id=report_id)
                print(report_id)


if __name__ == "__main__":
    main()
